training:
  name: doubledqn
  gym_id: MsPacmanDeterministic-v0
  num_episodes: 12240
  forbid_death: true
model:
  learning_rate: 1e-4
  gamma: 0.99
  epsilon: 1.0
  epsilon_end: 0.05
  epsilon_decay: 8.62e-5
  batch_size: 32
  replace_every: 1000
  memory_gb: 3
checkpoints:
  path: ../data/checkpoints/
  max_size: 5
  every: 500
logs:
  path: ../data/logs/
monitor:
  path: ../data/monitor/
evaluation:
  num_episodes: 200
