training:
  gym_id: Breakout-v4
  num_episodes: 4000
model:
  learning_rate: 1e-4
  gamma: 0.99
  epsilon: 1.0
  epsilon_end: 0.1
  epsilon_decay: 1e-5
  batch_size: 32
  replace_every: 500
  memory_gb: 3
checkpoints:
  path: ../data/checkpoints/
  every: 500
  on_highscore: True
logs:
  path: ../data/logs/
monitor:
  path: ../data/monitor/
plots:
  path: ../data/plots/
